### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jhumbrac**

### CODE REVIEW

**Comment by tc50** [comment]
Oops I thought I had to comment on this in order to save it!! Haha, I meant to write it as if this was the change with "Jon's help". I am totally confused as to what I should do with this pull request from last week!

**Comment by tc50** [comment]
I had no idea this was a comment as in a chat!

**Comment by jhumbrac** [comment]
no worries. you went one screen too far. there's a green button that says
merge pull request. click on that and then click confirm merge. after that
you need to sync your app before working locally. don't need to make a
summary or anything when you merge a pull request

john

**Comment by tc50** [comment]
Thanks, John!

**Comment by tc50** [comment]
I don't see it though. When I click on the link, I come to this page. When I click on Pull Requests, I get to a page that says "Bummer we couldn't find anything"

**Comment by jhumbrac** [comment]
on that page you should see a pull requests option on the right hand side
of the screen. my github is saying you still have 2 pull requests
outstanding. i'm not talking about the notifications option at the top. on
the right hand side (when you're in your repo and not the landing page) is
an icon menu. one of them looks sort of like a subway map. anyways, when
you hover over them you'll see what each one is. click the one that says
pull requests and you should see the two pull requests

john

**Comment by tc50** [comment]
I don't know what's going on but for some reason I can pull up the pull requests but don't see a button to merge them.

**Pull request closed without merging**
